<?php

namespace App\Imports;

use App\Models\Variant;
use App\Models\SizeOption;
use App\Models\Stock;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Illuminate\Support\Facades\DB;
use Exception;

class StockUpdateImport implements ToCollection, WithHeadingRow
{
    public function collection(Collection $rows)
    {
        $sizes = SizeOption::all()->keyBy(function($item) {
            // Excel heading row converts spaces to underscores and lowercases automatically
            return strtolower(str_replace([' ', '.'], '_', $item->name));
        });

        DB::beginTransaction();

        try {
            foreach ($rows as $row) {
                // Determine headers used in the excel. HeadingRow automatically snake_cases.
                
                $variantId = $row['variant_id'] ?? null;
                $variantCode = $row['variant_code'] ?? null;
                
                // Identify and skip trailing empty rows generated by Excel
                $isEmptyRow = true;
                foreach ($row->toArray() as $value) {
                    if ($value !== null && trim((string)$value) !== '') {
                        $isEmptyRow = false;
                        break;
                    }
                }

                if ($isEmptyRow) {
                    continue;
                }

                $productName = $row['product_name'] ?? 'Unknown';

                if (!$variantId && !$variantCode) {
                    throw new Exception("Invalid data: variant_id and variant_code missing for product '{$productName}'.");
                }

                $variant = null;
                if ($variantId) {
                    $variant = Variant::find($variantId);
                }
                if (!$variant && $variantCode) {
                    $variant = Variant::where('variant_code', $variantCode)->first();
                }

                if (!$variant) {
                    throw new Exception("Invalid data: variant or product not found (Product: {$productName})");
                }

                // Strictly update Stocks based on dynamic sizes
                foreach ($sizes as $excelKey => $sizeOpt) {
                    // Check if this size exists in excel headers
                    if (isset($row[$excelKey]) || array_key_exists($excelKey, $row->toArray())) {
                        Stock::updateOrCreate(
                            [
                                'variant_id' => $variant->id,
                                'size_option_id' => $sizeOpt->id,
                            ],
                            [
                                'stock' => max(0, intval($row[$excelKey])),
                            ]
                        );
                    }
                }
            }

            DB::commit();
        } catch (\Exception $e) {
            DB::rollBack();
            throw $e;
        }
    }
}
